### ISSUE TITLE
Verisioning thoughts

### ISSUE THREAD

**Issue by auniverseaway** [adobe/da-admin#37]
1. Be able to rollback to version -1, -X, etc.
2. New version on delete
3. Document best practices - always make a version as part of any migration script
4. Copy should not retain the source versions

**Comment by bosschaert** [comment]
@auniverseaway regarding your points:

1. This is currently possible with the version restore, no more work needed here I think.
2. A new version on delete is currently already created (see https://github.com/adobe/da-admin/blob/main/src/routes/source.js#L28 ) however there is no mechanism to retrieve it yet, so I created #55 for that.
3. I think the best practice lies outside of the `da-admin` code itself, no?
4. I created a new issue for this: #56

**Comment by bosschaert** [comment]
@auniverseaway I think we can close this issue, right?
