### ISSUE TITLE
Local Dev S3 Store

### ISSUE THREAD

**Issue by auniverseaway** [adobe/da-admin#4]
As a developer working locally, I would like to work against a local copy of S3 buckets so that I do not have to worry about security concerns over having A) access tokens, B) live customer data.

## Criteria of acceptance
1. Developing locally uses a local S3 store (Docker S3 Mock?) instead of live customer data.
2. Documentation on local development process (TLDR & detailed)
3. Nice to have: One command to run after initial setup... `npm run dev` starts local docker instance & da-admin.

**Comment by bstopp** [comment]
This won't be needed any more with the move to R2 native bindings.
