### ISSUE TITLE
Version history behaviors

### ISSUE THREAD

**Issue by auniverseaway** [adobe/da-admin#88]
1. If you copy, the copy gets fresh history.
1. If you copy to replace, the copy inherits the replaced history.
1. If you move, the history moves with it.

From @bosschaert: 1 & 3 are already the behavior.

Number 2 will need to be implemented.

**Comment by bosschaert** [comment]
On `2.` above, what do you mean exactly? Replacing the content of an existing document with the content of another existing document, without replacing the target document's history? Because that is exactly what you get when you simply call `PUT` on a `/source/...` URL?

**Comment by bosschaert** [comment]
I worked on a prototype with @karlpauls during the AdaptTo conference last week. Plan is it finish this and create a PR.
